Added liquibase changelogs
AlexRosenkreuz/OnlineBookStore pull request #8
Opened 2023-11-08 17:07 UTC by AlexRosenkreuz

Added liquibase changelogs for Categories table and Joined Category-Book table. Created Categories model. Added JPA repo and mapper. Created DTO layer for requests. Updated existing BookMapper. Added controller and service for Categories

2023-11-10 09:02 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/java/com/foalex/bookstore/mapper/CategoryMapper.java
> +}
how does your check style miss it?

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/java/com/foalex/bookstore/service/CategoryService.java
> +    List<BookDtoWithoutCategories> findBooksByCategoryId(Long id, Pageable pageable);
it should be a method of book service

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/java/com/foalex/bookstore/service/impl/BookServiceImpl.java
> +    public List<BookDto> findAll(@PageableDefault Pageable pageable) {
move this annotation  to controller level

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/java/com/foalex/bookstore/service/impl/BookServiceImpl.java
> +                             Book with id %d doesn't exist.""".formatted(id)));
it would be best if you moved it to a private method to avoid code duplicate

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/java/com/foalex/bookstore/service/impl/CategoryServiceImpl.java
> +        }
Let’s remove this check. You should return an empty collection not throw an exception

2023-11-10 09:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/07-create-books-categories-table.yaml
add one empty line

2023-11-27 04:28 UTC, AlexRosenkreuz commented on src/main/java/com/foalex/bookstore/service/impl/BookServiceImpl.java
> +                             Book with id %d doesn't exist.""".formatted(id)));
I've tried to do this. Have come up with something, that works and preserves original logic

2023-11-27 15:38 UTC, Elena-Bruyako approved these changes
Good job!

2023-11-29 01:19 UTC, merged